// Static entity schemas for admin forms (the SDK has no runtime schema() call).
export const entitySchemas = {
  Product: {
    properties: {
      name: { type: 'string' },
      sku: { type: 'string' },
      category: { type: 'string', enum: ['Theatre Equipment', 'ICU Equipment', 'Emergency Equipment', 'Orthopaedic Devices', 'Diagnostic Equipment', 'Cardiology Equipment', 'Laboratory Equipment', 'Radiology Equipment', 'Digital Health Systems', 'CSSD Equipment', 'Oncology Equipment', 'General Ward Equipment', 'Maternal & Infant Care', 'Anaesthesia Systems', 'Surgical Instruments & Disposables'] },
      subcategory: { type: 'string' },
      short_description: { type: 'string' },
      full_description: { type: 'string' },
      features: { type: 'array', items: { type: 'string' } },
      images: { type: 'array', items: { type: 'string' } },
      thumbnail: { type: 'string' },
      brochure_url: { type: 'string' },
      video_url: { type: 'string' },
      manufacturer: { type: 'string' },
      country_of_origin: { type: 'string' },
      certifications: { type: 'array', items: { type: 'string' } },
      is_featured: { type: 'boolean' },
      is_new: { type: 'boolean' },
      status: { type: 'string', enum: ['active', 'discontinued', 'coming_soon'] },
      tags: { type: 'array', items: { type: 'string' } },
    },
  },
  NewsArticle: {
    properties: {
      title: { type: 'string' },
      slug: { type: 'string' },
      category: { type: 'string', enum: ['Healthcare News', 'Medical Innovations', 'Industry Reports', 'Case Studies', 'Company News', 'Research Articles', 'White Papers', 'Events'] },
      excerpt: { type: 'string' },
      body: { type: 'string' },
      cover_image: { type: 'string' },
      author_name: { type: 'string' },
      author_title: { type: 'string' },
      author_photo: { type: 'string' },
      published_date: { type: 'string', format: 'date' },
      is_featured: { type: 'boolean' },
      tags: { type: 'array', items: { type: 'string' } },
      status: { type: 'string', enum: ['draft', 'published', 'archived'] },
      read_time_minutes: { type: 'number' },
    },
  },
  Event: {
    properties: {
      title: { type: 'string' },
      event_type: { type: 'string', enum: ['Conference', 'Exhibition', 'Workshop', 'Webinar', 'Training', 'Healthcare Summit', 'Product Launch', 'Trade Show'] },
      description: { type: 'string' },
      start_date: { type: 'string', format: 'date' },
      end_date: { type: 'string', format: 'date' },
      location: { type: 'string' },
      venue: { type: 'string' },
      is_virtual: { type: 'boolean' },
      registration_url: { type: 'string' },
      cover_image: { type: 'string' },
      max_attendees: { type: 'number' },
      status: { type: 'string', enum: ['upcoming', 'ongoing', 'completed', 'cancelled'] },
      is_featured: { type: 'boolean' },
      tags: { type: 'array', items: { type: 'string' } },
    },
  },
  ServiceRequest: {
    properties: {
      ticket_number: { type: 'string' },
      request_type: { type: 'string', enum: ['Preventive Maintenance', 'Equipment Repair', 'Calibration', 'Installation', 'Compliance Testing', 'Technical Support', 'Warranty Claim', 'Emergency Service'] },
      description: { type: 'string' },
      equipment_name: { type: 'string' },
      equipment_serial: { type: 'string' },
      location: { type: 'string' },
      priority: { type: 'string', enum: ['Low', 'Medium', 'High', 'Critical'] },
      status: { type: 'string', enum: ['open', 'in_progress', 'pending_parts', 'resolved', 'closed'] },
      assigned_engineer: { type: 'string' },
      scheduled_date: { type: 'string', format: 'date' },
      resolved_date: { type: 'string', format: 'date' },
      resolution_notes: { type: 'string' },
      attachment_url: { type: 'string' },
    },
  },
  Download: {
    properties: {
      title: { type: 'string' },
      category: { type: 'string', enum: ['Product Catalogue', 'Brochure', 'White Paper', 'Certificate', 'Technical Document', 'Training Manual', 'Installation Guide', 'Compliance Document'] },
      description: { type: 'string' },
      file_url: { type: 'string' },
      file_type: { type: 'string' },
      file_size: { type: 'string' },
      language: { type: 'string' },
      product_category: { type: 'string' },
      cover_image: { type: 'string' },
      is_public: { type: 'boolean' },
      download_count: { type: 'number' },
    },
  },
  CaseStudy: {
    properties: {
      title: { type: 'string' },
      client_name: { type: 'string' },
      client_logo: { type: 'string' },
      industry: { type: 'string', enum: ['Public Healthcare', 'Private Healthcare', 'Academic Healthcare', 'Military Healthcare', 'Specialist Care', 'Primary Healthcare', 'NGO'] },
      location: { type: 'string' },
      challenge: { type: 'string' },
      solution: { type: 'string' },
      results: { type: 'string' },
      products_used: { type: 'array', items: { type: 'string' } },
      cover_image: { type: 'string' },
      images: { type: 'array', items: { type: 'string' } },
      testimonial_quote: { type: 'string' },
      testimonial_author: { type: 'string' },
      testimonial_title: { type: 'string' },
      is_featured: { type: 'boolean' },
      status: { type: 'string', enum: ['draft', 'published'] },
    },
  },
  QuoteRequest: {
    properties: {
      first_name: { type: 'string' },
      last_name: { type: 'string' },
      email: { type: 'string' },
      phone: { type: 'string' },
      organization: { type: 'string' },
      job_title: { type: 'string' },
      organization_type: { type: 'string', enum: ['Public Hospital', 'Private Hospital', 'Clinic', 'Government Department', 'NGO', 'University', 'Research Institution', 'Distributor', 'Other'] },
      products_interested: { type: 'array', items: { type: 'string' } },
      product_categories: { type: 'array', items: { type: 'string' } },
      project_description: { type: 'string' },
      budget_range: { type: 'string', enum: ['Under R500K', 'R500K - R2M', 'R2M - R10M', 'R10M - R50M', 'Over R50M', 'Not Specified'] },
      province: { type: 'string' },
      country: { type: 'string' },
      timeline: { type: 'string', enum: ['Immediate (0-3 months)', 'Short-term (3-6 months)', 'Medium-term (6-12 months)', 'Long-term (12+ months)', 'Planning Phase'] },
      additional_notes: { type: 'string' },
      attachment_url: { type: 'string' },
      status: { type: 'string', enum: ['new', 'in_review', 'quoted', 'won', 'lost', 'on_hold'] },
      assigned_to: { type: 'string' },
      internal_notes: { type: 'string' },
    },
  },
  JobListing: {
    properties: {
      title: { type: 'string' },
      department: { type: 'string', enum: ['Clinical Engineering', 'Sales', 'Technical Support', 'Operations', 'Finance', 'Human Resources', 'Marketing', 'IT', 'Logistics', 'Management'] },
      location: { type: 'string' },
      employment_type: { type: 'string', enum: ['Full-time', 'Part-time', 'Contract', 'Internship', 'Graduate Programme'] },
      description: { type: 'string' },
      requirements: { type: 'array', items: { type: 'string' } },
      responsibilities: { type: 'array', items: { type: 'string' } },
      benefits: { type: 'array', items: { type: 'string' } },
      salary_range: { type: 'string' },
      closing_date: { type: 'string', format: 'date' },
      status: { type: 'string', enum: ['open', 'closed', 'filled'] },
      is_featured: { type: 'boolean' },
    },
  },
};