export const allProducts = [
  // ── EXISTING PRODUCTS ──────────────────────────────────────────────────────
  { id: 1, name: 'IntelliVue MX750 Patient Monitor', sku: 'PHL-MX750', category: 'Diagnostic Equipment', manufacturer: 'Philips', country: 'Netherlands', image: 'https://images.unsplash.com/photo-1576669801820-a9ab287ac2d1?w=900&q=80', description: 'High-acuity patient monitoring with advanced waveform analysis and networked EMR integration.', fullDescription: 'The IntelliVue MX750 is a high-acuity patient monitor designed for critical care environments. It delivers advanced waveform analysis, comprehensive alarm management, and seamless networked EMR integration. Featuring a large high-resolution display, the MX750 supports a wide range of measurements including ECG, SpO2, NIBP, IBP, temperature, and respiratory parameters.', features: ['12.1" high-resolution touchscreen display', 'Advanced arrhythmia detection and analysis', 'Integrated 12-lead resting ECG', 'Bi-directional EMR data exchange', 'Smart Alarm Management System', 'Real-time trending and predictive alerts', 'WiFi and wired LAN connectivity', 'Modular expandability'], specs: [{ label: 'Display', value: '12.1" touchscreen' }, { label: 'Parameters', value: 'ECG, SpO2, NIBP, IBP, Temp, EtCO2' }, { label: 'Battery', value: '8 hours' }, { label: 'Weight', value: '6.2 kg' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: false, isFeatured: true },
  { id: 2, name: 'Maquet Magnus Operating Table', sku: 'MQT-MAGNUS-1150', category: 'Theatre Equipment', manufacturer: 'Getinge', country: 'Sweden', image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=900&q=80', description: 'Carbon-fibre operating table with full imaging compatibility and 360° surgeon ergonomics.', fullDescription: 'The Maquet Magnus is a state-of-the-art operating table engineered for the modern surgical suite. Its carbon-fibre tabletop offers full X-ray and fluoroscopy transparency, while the precision electro-hydraulic positioning system provides 360° flexibility for every surgical discipline.', features: ['Carbon-fibre X-ray transparent tabletop', 'Electro-hydraulic 6-axis positioning', 'Maximum patient load: 360 kg', 'Lateral tilt ±30°, Trendelenburg ±35°', 'Integrated lateral positioning aids', 'Removable and exchangeable table sections', 'Compatible with all major C-arm systems', 'Stainless steel column for easy cleaning'], specs: [{ label: 'Max Load', value: '360 kg' }, { label: 'Table Height', value: '620–1020 mm' }, { label: 'Table Length', value: '2000 mm' }, { label: 'Lateral Tilt', value: '±30°' }, { label: 'Certifications', value: 'CE, ISO 13485, MDD' }], certifications: ['CE Mark', 'ISO 13485'], isNew: true, isFeatured: true },
  { id: 3, name: 'BeneVision N22 ICU Monitor', sku: 'MDR-BN22-ICU', category: 'ICU Equipment', manufacturer: 'Mindray', country: 'China', image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&q=80', description: 'Comprehensive critical care monitor with 22" display and full haemodynamic monitoring.', fullDescription: 'The BeneVision N22 is Mindray\'s flagship bedside monitor for intensive care. With a 22" Full-HD touchscreen and a comprehensive suite of haemodynamic parameters, it provides clinicians with a complete physiological picture.', features: ['22" Full-HD touchscreen display', 'Advanced haemodynamic monitoring (PiCCO, FloTrac)', '12-lead ECG with ST/arrhythmia analysis', 'Integrated patient data management', 'BeneLink connectivity for device integration', 'HL7 and DICOM support', 'Dedicated NICU neonatal mode', 'Smart discharge summary reports'], specs: [{ label: 'Display', value: '22" Full-HD touchscreen' }, { label: 'Parameters', value: 'ECG, SpO2, NIBP, IBP, Temp, EtCO2, PiCCO' }, { label: 'Battery', value: '4+ hours' }, { label: 'Weight', value: '11.5 kg' }, { label: 'Certifications', value: 'CE, FDA, NMPA' }], certifications: ['CE Mark', 'FDA 510(k)', 'NMPA'], isNew: false, isFeatured: true },
  { id: 4, name: 'GE Logiq E10 Ultrasound', sku: 'GE-LOGIQ-E10', category: 'Radiology Equipment', manufacturer: 'GE Healthcare', country: 'USA', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80', description: 'Premium shared-service ultrasound with AI-assisted imaging and cSound architecture.', fullDescription: 'The LOGIQ E10 represents GE\'s most advanced ultrasound platform, powered by cSound architecture and AI-enhanced imaging. The Radiology Reimagined interface streamlines workflow, while Precision Imaging automatically optimises image quality.', features: ['cSound architecture for superior image quality', 'AI-assisted Auto Optimization', 'Radiology Reimagined user interface', 'Shear Wave Elastography', 'Contrast Enhanced Ultrasound (CEUS)', '4D volume imaging', 'Integrated reporting tools', 'DICOM 3.0 connectivity'], specs: [{ label: 'Probes', value: 'Broadband probes 1–24 MHz' }, { label: 'Display', value: '23" touchscreen' }, { label: 'Modes', value: 'B, M, CFM, PW, CW, 3D/4D' }, { label: 'Weight', value: '115 kg' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: true, isFeatured: false },
  { id: 5, name: 'Draeger Evita 800 Ventilator', sku: 'DRG-EVITA-800', category: 'ICU Equipment', manufacturer: 'Dräger', country: 'Germany', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&q=80', description: 'High-end ICU ventilator with integrated lung mechanics and advanced closed-loop ventilation.', fullDescription: 'The Evita 800 is Dräger\'s premium ICU ventilator, incorporating advanced lung-protective ventilation strategies and closed-loop ventilation modes. SmartCare/PS automated weaning significantly reduces weaning time.', features: ['SmartCare/PS automated weaning', 'Closed-loop ventilation (AutoFlow, SPN-CPAP/PS)', 'Advanced lung mechanics monitoring', 'NeoFlow neonatal option', 'CO2 monitoring integration', 'Built-in nebuliser', 'Neonatal to adult patient range (0.3–200 kg)', '15" touchscreen display'], specs: [{ label: 'Flow Range', value: '0–200 L/min' }, { label: 'Tidal Volume', value: '2–2000 mL' }, { label: 'PEEP Range', value: '0–50 hPa' }, { label: 'Display', value: '15" touchscreen' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: false, isFeatured: true },
  { id: 6, name: 'Siemens ACUSON Sequoia', sku: 'SIE-ACU-SEQ', category: 'Radiology Equipment', manufacturer: 'Siemens Healthineers', country: 'Germany', image: 'https://images.unsplash.com/photo-1628348070889-cb656235b4eb?w=900&q=80', description: 'Revolutionary ultrasound with BioAcoustic Imaging for unprecedented image quality.', fullDescription: 'The ACUSON Sequoia redefines ultrasound imaging through BioAcoustic Imaging technology, delivering exceptional penetration and resolution even in the most challenging patients.', features: ['BioAcoustic Imaging technology', 'DirectConnect wireless transducer interface', 'Acoustic Intelligence auto-optimization', 'eSieScan one-button auto-optimization', 'Advanced elastography suite', 'Contrast-enhanced ultrasound', 'Ergonomic floating console', 'AI-powered measurements'], specs: [{ label: 'Technology', value: 'BioAcoustic Imaging' }, { label: 'Display', value: '21.5" HD monitor' }, { label: 'Frequency Range', value: '1–24 MHz' }, { label: 'Weight', value: '110 kg' }, { label: 'Certifications', value: 'CE, FDA' }], certifications: ['CE Mark', 'FDA 510(k)'], isNew: false, isFeatured: false },
  { id: 7, name: 'Stryker 3202 LED Surgical Light', sku: 'STR-3202-LED', category: 'Theatre Equipment', manufacturer: 'Stryker', country: 'USA', image: 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=900&q=80', description: 'High-output LED surgical ceiling light with integrated camera system and shadow-free illumination.', fullDescription: 'The Stryker 3202 LED surgical light delivers exceptional illumination for complex surgical procedures. Its advanced LED array produces shadow-free, colour-corrected light that closely mimics daylight, reducing eye fatigue for the surgical team.', features: ['180,000 lux maximum illumination', 'Shadow-free multi-LED array design', 'Colour temperature: 4,000–4,500 K', 'CRI > 96 for accurate tissue colour', 'Integrated HD surgical camera', 'Motion-sensing auto-focus', 'Sterile handle autoclavable at 134°C', 'Compatible with OR integration systems'], specs: [{ label: 'Illuminance', value: '180,000 lux' }, { label: 'Colour Temp', value: '4,000–4,500 K' }, { label: 'CRI', value: '>96' }, { label: 'LED Lifespan', value: '60,000+ hours' }, { label: 'Certifications', value: 'CE, UL, ISO 13485' }], certifications: ['CE Mark', 'UL Listed', 'ISO 13485'], isNew: false, isFeatured: false },
  { id: 8, name: 'Defibrillator LIFEPAK 20e', sku: 'STC-LP20E', category: 'Emergency Equipment', manufacturer: 'Stryker', country: 'USA', image: 'https://images.unsplash.com/photo-1571772996211-2f02974562f3?w=900&q=80', description: 'Professional defibrillator/monitor with CPR feedback and protocol-driven therapy guidance.', fullDescription: 'The LIFEPAK 20e is a professional-grade defibrillator and monitor trusted in emergency departments, ICUs, and crash carts worldwide. It features ADAPTIV biphasic technology for effective defibrillation and real-time CPR feedback.', features: ['ADAPTIV biphasic defibrillation technology', 'CPR Dashboard with real-time feedback', 'CPRD automated CPR coaching', 'AED and manual modes', '3/12-lead ECG monitoring', 'External pacing capability', 'Portable lightweight design (5.7 kg)', 'Optional CO2, SpO2, NIBP monitoring'], specs: [{ label: 'Energy Range', value: '2–360 J (biphasic)' }, { label: 'ECG', value: '3 and 12-lead' }, { label: 'Weight', value: '5.7 kg' }, { label: 'Battery Life', value: '3 hours monitoring' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: false, isFeatured: false },
  { id: 9, name: 'ICU Hospital Bed Eleganza 5', sku: 'HRD-ELEG5-ICU', category: 'ICU Equipment', manufacturer: 'Stiegelmeyer', country: 'Germany', image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=900&q=80', description: 'Advanced ICU bed with integrated scales, auto-lateral tilt therapy, and nurse control panels.', fullDescription: 'The Eleganza 5 is a premium ICU bed engineered for the highest level of patient care. Integrated scales eliminate the need for patient transfers during weighing, while automatic lateral tilt therapy supports lung recruitment and pressure ulcer prevention.', features: ['Integrated bed weighing scales (±0.5 kg accuracy)', 'Automatic lateral tilt therapy (±30°)', 'CPR-ready position in <5 seconds', 'Nurse-controlled position presets', 'Built-in nurse call integration', 'X-ray cassette holder', 'Electric height adjustment 380–850 mm', 'Side rail with integrated controls'], specs: [{ label: 'Height Range', value: '380–850 mm' }, { label: 'Max Load', value: '300 kg' }, { label: 'Lateral Tilt', value: '±30°' }, { label: 'Scale Accuracy', value: '±0.5 kg' }, { label: 'Certifications', value: 'CE, ISO 13485' }], certifications: ['CE Mark', 'ISO 13485'], isNew: true, isFeatured: false },
  { id: 10, name: 'Biomet Vanguard Knee System', sku: 'ZIM-VNG-KNEE', category: 'Orthopaedic Devices', manufacturer: 'Zimmer Biomet', country: 'USA', image: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=900&q=80', description: 'Complete primary knee replacement system with MyKnee patient-specific cutting guides.', fullDescription: 'The Vanguard Complete Knee System offers unmatched versatility for primary total knee arthroplasty. Combined with MyKnee patient-specific instrumentation, it enables precise, reproducible bone cuts tailored to each patient\'s anatomy.', features: ['Patient-specific MyKnee cutting guides', 'Optimised polyethylene bearing options', 'Gender-specific femoral component designs', 'Medial-Pivot kinematics option', 'Tibial stem extension options', 'Revision conversion compatibility', 'Wide implant size range (5 sizes)', 'Cobalt-Chrome and Oxinium bearing options'], specs: [{ label: 'Material', value: 'CoCrMo alloy / Oxinium' }, { label: 'Sizes', value: '5 femoral, 6 tibial' }, { label: 'Bearing Options', value: 'PS, CR, MP' }, { label: 'Sterilisation', value: 'Gamma irradiation' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: false, isFeatured: false },
  { id: 11, name: 'Abbott Architect c8000', sku: 'ABT-ARCH-C8000', category: 'Laboratory Equipment', manufacturer: 'Abbott', country: 'USA', image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=900&q=80', description: 'High-throughput clinical chemistry analyser for large-volume hospital laboratories.', fullDescription: 'The ARCHITECT c8000 is a continuous access, random-access chemistry analyser offering 800 photometric tests per hour. It supports the full ARCHITECT chemistry menu of over 100 assays and integrates seamlessly into laboratory automation lines.', features: ['800 photometric tests/hour throughput', 'Continuous sample access — no interruption to run', 'Integrated liquid level sensing', 'Automatic reagent mixing', 'Full bidirectional LIS connectivity', 'Onboard reagent refrigeration (2–8°C)', 'Reagent inventory management', 'Automated QC flagging'], specs: [{ label: 'Throughput', value: '800 tests/hour' }, { label: 'Sample Volume', value: '2–35 µL' }, { label: 'Reagent Capacity', value: '60 reagent positions' }, { label: 'Temperature', value: '37°C ± 0.1°C' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: false, isFeatured: false },
  { id: 12, name: 'Siemens Healthineers ECG 12-Lead', sku: 'SIE-ECG-12L', category: 'Cardiology Equipment', manufacturer: 'Siemens Healthineers', country: 'Germany', image: 'https://images.unsplash.com/photo-1628348070889-cb656235b4eb?w=900&q=80', description: 'Resting ECG system with Aris AI interpretation and EMR connectivity for cardiology departments.', fullDescription: 'The Siemens Healthineers resting ECG system with ARIS AI interpretation provides fast, accurate 12-lead ECG acquisition with automated clinical interpretation. Seamless EMR integration ensures immediate availability of ECG data in the patient record.', features: ['AI-powered ARIS ECG interpretation', 'Bluetooth and WiFi connectivity', 'Large colour touchscreen display', 'Full 12-lead simultaneous acquisition', 'Automated measurements and intervals', 'Bi-directional EMR/HIS integration', 'Built-in rechargeable battery', 'PDF and DICOM ECG export'], specs: [{ label: 'Leads', value: '12-lead simultaneous' }, { label: 'Sample Rate', value: '1000 samples/sec' }, { label: 'Display', value: '10.4" colour touchscreen' }, { label: 'Connectivity', value: 'WiFi, Bluetooth, LAN' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }], certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'], isNew: true, isFeatured: false },

  // ── DIGITAL HEALTH SYSTEMS ─────────────────────────────────────────────────
  {
    id: 13,
    name: 'Cerner Millennium EMR Platform',
    sku: 'CRN-MIL-EMR-ENT',
    category: 'Digital Health Systems',
    manufacturer: 'Oracle Cerner',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=900&q=80',
    description: 'Enterprise electronic medical records platform with clinical decision support and full hospital integration.',
    fullDescription: 'Cerner Millennium is the world\'s most widely deployed hospital information system, used in over 27,000 facilities across 35 countries. The platform delivers a comprehensive suite of clinical, administrative, and financial applications, all built on a single patient record. Integrated clinical decision support, AI-powered alerts, and real-time analytics help clinicians deliver safer, more effective care.',
    features: ['Unified patient record across all care settings', 'Clinical decision support with evidence-based alerts', 'AI-powered deterioration prediction (HealtheIntent)', 'Integrated CPOE with drug interaction checking', 'Real-time nursing documentation', 'Mobile physician and nursing applications', 'Bi-directional laboratory and radiology integration', 'Population health management analytics'],
    specs: [{ label: 'Deployment', value: 'Cloud, On-premise, Hybrid' }, { label: 'HL7 Version', value: 'HL7 FHIR R4, v2.x' }, { label: 'Modules', value: '40+ clinical and administrative' }, { label: 'Uptime SLA', value: '99.9%' }, { label: 'Certifications', value: 'ONC-certified, ISO 27001, HIPAA' }],
    certifications: ['ONC Certified', 'ISO 27001', 'HIPAA Compliant'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: 14,
    name: 'Philips HealthSuite Telehealth Platform',
    sku: 'PHL-HSP-TELE-PRO',
    category: 'Digital Health Systems',
    manufacturer: 'Philips',
    country: 'Netherlands',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&q=80',
    description: 'Comprehensive telehealth and remote patient monitoring platform for hospital-to-home care continuity.',
    fullDescription: 'Philips HealthSuite is an enterprise telehealth and remote patient monitoring platform that connects patients at home with their clinical care teams. Combining wearable biosensors, a patient-facing mobile app, and a clinician dashboard, it enables real-time monitoring of chronic conditions, post-discharge care, and virtual consultations — reducing readmissions and expanding care access.',
    features: ['Real-time vital sign monitoring via wearables', 'Video consultation with HD quality', 'AI-powered early warning scoring', 'Automated care pathway adherence tracking', 'Secure patient messaging and education', 'Integration with major EMR platforms', 'FDA-cleared monitoring algorithms', 'HIPAA-compliant data architecture'],
    specs: [{ label: 'Video Quality', value: 'HD 1080p video consultations' }, { label: 'Monitoring Parameters', value: 'HR, SpO2, RR, BP, Weight, ECG' }, { label: 'App Platforms', value: 'iOS and Android' }, { label: 'Integration', value: 'HL7 FHIR, Epic, Cerner' }, { label: 'Certifications', value: 'CE, FDA, ISO 27001' }],
    certifications: ['CE Mark', 'FDA Cleared', 'ISO 27001'],
    isNew: true,
    isFeatured: false,
  },
  {
    id: 15,
    name: 'Zebra TC52 Healthcare Mobile Computer',
    sku: 'ZBR-TC52-HC-R2',
    category: 'Digital Health Systems',
    manufacturer: 'Zebra Technologies',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&q=80',
    description: 'Rugged healthcare mobile computer for bedside barcode scanning, medication administration, and EMR access.',
    fullDescription: 'The Zebra TC52 Healthcare Mobile Computer is purpose-built for clinical environments. Its antimicrobial housing survives repeated disinfection with hospital-grade solutions, while the enterprise-class barcode scanner enables rapid, accurate medication administration verification, patient identification wristband scanning, and specimen labelling at the point of care.',
    features: ['Antimicrobial Corning Gorilla Glass display', 'Enterprise-class 1D/2D barcode scanner', 'Long-shift 14-hour battery life', 'IP65 water and dust resistance', 'Disinfectant-ready housing', 'Android enterprise with managed updates', 'Integrated NFC for smart card access', 'Drop-rated to 1.8 m on concrete'],
    specs: [{ label: 'OS', value: 'Android 10 GMS' }, { label: 'Display', value: '5.0" FHD touchscreen' }, { label: 'Scanner', value: '1D/2D SE4710 imager' }, { label: 'Battery', value: '4150 mAh (14 hours)' }, { label: 'Certifications', value: 'CE, FCC, IP65' }],
    certifications: ['CE Mark', 'FCC', 'IP65 Rated'],
    isNew: false,
    isFeatured: false,
  },

  // ── CSSD EQUIPMENT ─────────────────────────────────────────────────────────
  {
    id: 16,
    name: 'Getinge GSS67H Steam Steriliser',
    sku: 'GTG-GSS67H-CSSD',
    category: 'CSSD Equipment',
    manufacturer: 'Getinge',
    country: 'Sweden',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&q=80',
    description: 'High-capacity pre-vacuum steam steriliser for surgical instruments with integrated cycle documentation.',
    fullDescription: 'The Getinge GSS67H is a large-format, high-throughput pre-vacuum steam steriliser designed for busy CSSD departments. With a 671-litre chamber capacity and dual-door pass-through configuration, it enables seamless dirty-to-clean workflow separation. Automated cycle documentation and LIS integration ensure complete traceability of every sterilisation batch.',
    features: ['671-litre double-door pass-through chamber', 'Pre-vacuum air removal for hollow instruments', 'Automated cycle documentation and batch records', 'Integrated LIS/CSSD tracking system connectivity', 'Drying programme for porous and non-porous loads', 'Data logging with tamper-evident records', 'Self-test and automatic validation cycles', 'Low water consumption eco programme'],
    specs: [{ label: 'Chamber Volume', value: '671 litres (2×3 STE)' }, { label: 'Temperature Range', value: '121°C and 134°C' }, { label: 'Cycle Time', value: '134°C: ~35 min' }, { label: 'Steam Supply', value: 'Hospital steam or integrated generator' }, { label: 'Certifications', value: 'CE, EN 13060, ISO 17665' }],
    certifications: ['CE Mark', 'EN 13060', 'ISO 17665'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 17,
    name: 'Miele PG 8536 Washer-Disinfector',
    sku: 'MIE-PG8536-WD',
    category: 'CSSD Equipment',
    manufacturer: 'Miele Professional',
    country: 'Germany',
    image: 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=900&q=80',
    description: 'Large-capacity washer-disinfector for surgical instruments with validated A0 600 thermal disinfection.',
    fullDescription: 'The Miele PG 8536 is a large-capacity, thermally disinfecting washer-disinfector validated to A0 600, meeting the gold standard for thermal disinfection of surgical instruments, anaesthesia accessories, and rigid endoscopes. Its modular basket system accommodates a wide variety of instrument sets, while the web-based reporting module enables complete batch traceability.',
    features: ['A0 600 validated thermal disinfection', 'Large pass-through chamber (3 basket levels)', 'Modular basket system for all instrument types', 'Validated drying cycle with HEPA-filtered air', 'Integrated conductivity monitoring of water quality', 'Web-based batch documentation and reporting', 'Self-cleaning programme', 'Compatible with Miele lumen irrigation systems'],
    specs: [{ label: 'Capacity', value: '3 DIN basket levels' }, { label: 'Disinfection', value: 'A0 600 thermal' }, { label: 'Temperature', value: 'Up to 93°C' }, { label: 'Water Consumption', value: '~45 L per cycle' }, { label: 'Certifications', value: 'CE, EN ISO 15883, ISO 13485' }],
    certifications: ['CE Mark', 'EN ISO 15883', 'ISO 13485'],
    isNew: true,
    isFeatured: false,
  },
  {
    id: 18,
    name: 'Belimed WD 290 Endoscope Reprocessor',
    sku: 'BLM-WD290-ENDO',
    category: 'CSSD Equipment',
    manufacturer: 'Belimed',
    country: 'Switzerland',
    image: 'https://images.unsplash.com/photo-1576669801820-a9ab287ac2d1?w=900&q=80',
    description: 'Automated endoscope reprocessor with complete lumen irrigation and high-level disinfection documentation.',
    fullDescription: 'The Belimed WD 290 is an automated endoscope washer-disinfector purpose-built for flexible and semi-rigid endoscopes. Each cycle delivers validated lumen irrigation, enzymatic pre-cleaning, full channel flushing with high-level disinfectant, and complete rinse and drying — all fully documented for regulatory compliance and patient safety.',
    features: ['Validated lumen irrigation for all channels', 'High-level disinfection with OPA or peracetic acid', 'Scope-specific adaptor management system', 'Full batch documentation with scope tracking', 'RFID endoscope identification', 'Leak test integration', 'Automatic disinfectant concentration monitoring', 'Single-use disinfectant cartridge system'],
    specs: [{ label: 'Capacity', value: '2 flexible endoscopes per cycle' }, { label: 'Disinfectant', value: 'OPA, PAA compatible' }, { label: 'Cycle Time', value: '~28 min' }, { label: 'Documentation', value: 'Automatic batch records' }, { label: 'Certifications', value: 'CE, EN ISO 15883-4, ISO 13485' }],
    certifications: ['CE Mark', 'EN ISO 15883-4', 'ISO 13485'],
    isNew: false,
    isFeatured: false,
  },

  // ── ONCOLOGY EQUIPMENT ─────────────────────────────────────────────────────
  {
    id: 19,
    name: 'Varian TrueBeam Linear Accelerator',
    sku: 'VAR-TB-LINAC-HD',
    category: 'Oncology Equipment',
    manufacturer: 'Varian Medical Systems',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80',
    description: 'Advanced linear accelerator for IMRT, VMAT, and stereotactic radiosurgery with sub-millimetre precision.',
    fullDescription: 'The Varian TrueBeam is the industry-leading linear accelerator for modern radiation therapy. Its HyperArc radiosurgery system enables fully automated, high-definition stereotactic radiosurgery to multiple brain metastases in a single session, while the full suite of IMRT and VMAT delivery modes supports all tumour sites with sub-millimetre geometric accuracy.',
    features: ['HyperArc automated radiosurgery system', 'Sub-millimetre geometric accuracy', 'IMRT, VMAT, SBRT, SRS delivery modes', 'Real-time respiratory gating', 'On-board imaging: CBCT, MV portal imaging', 'Integrated surface guided radiotherapy (SGRT) option', 'Flattening filter free (FFF) beams — up to 2400 MU/min', 'Aria oncology information system integration'],
    specs: [{ label: 'Energy Range', value: '4–18 MV photons, 6–20 MeV electrons' }, { label: 'Max Dose Rate', value: '2400 MU/min (FFF 10 MV)' }, { label: 'MLC Leaf Width', value: '2.5 mm (HD120)' }, { label: 'Isocentric Accuracy', value: '<0.5 mm' }, { label: 'Certifications', value: 'CE, FDA, IEC 60601-2-1' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'IEC 60601-2-1'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: 20,
    name: 'BD Alaris Oncology Infusion System',
    sku: 'BD-ALR-ONCO-8015',
    category: 'Oncology Equipment',
    manufacturer: 'BD (Becton Dickinson)',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&q=80',
    description: 'Dedicated chemotherapy infusion pump system with drug library, dose error reduction, and full EMR integration.',
    fullDescription: 'The BD Alaris Oncology Infusion System is purpose-designed for chemotherapy administration. Its GuardRails drug library provides dose range checking for over 1,000 oncology agents, while bi-directional EMR integration ensures automatic order verification before infusion commences. The system supports simultaneous multi-channel infusion and integrates with pharmacy compounding systems.',
    features: ['GuardRails drug library with 1,000+ oncology agents', 'Bi-directional EMR order integration', 'Dose error reduction system (DERS)', 'Simultaneous 4-channel infusion', 'Tamper-evident drug administration logs', 'Auto-identification of chemotherapy orders', 'Wireless connectivity for remote programming updates', 'Integrated air-in-line and occlusion detection'],
    specs: [{ label: 'Channels', value: '4 simultaneous infusion channels' }, { label: 'Flow Rate', value: '0.1–999.9 mL/h' }, { label: 'Drug Library', value: '1,000+ oncology agents' }, { label: 'Connectivity', value: 'WiFi, Ethernet, HL7' }, { label: 'Certifications', value: 'CE, FDA, IEC 60601-1' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'IEC 60601-1'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 21,
    name: 'Elekta Versa HD Radiotherapy System',
    sku: 'ELK-VHD-RT-SYS',
    category: 'Oncology Equipment',
    manufacturer: 'Elekta',
    country: 'Sweden',
    image: 'https://images.unsplash.com/photo-1571772996211-2f02974562f3?w=900&q=80',
    description: 'High-definition radiotherapy system for IMRT, VMAT, and SRS with Agility 160-leaf MLC.',
    fullDescription: 'The Elekta Versa HD combines the Agility 160-leaf MLC, a 2.5 mm leaf width high-definition multi-leaf collimator, with flattening filter free (FFF) beam delivery to deliver precise radiotherapy at high dose rates. Integrated XVI imaging and Monaco treatment planning integration enables full adaptive radiotherapy workflows.',
    features: ['Agility 160-leaf MLC (2.5 mm leaf width)', 'FFF delivery at 2200 MU/min (10 MV)', 'XVI volumetric imaging for IGRT', 'Full IMRT, VMAT, SBRT, SRS capabilities', 'Monaco adaptive treatment planning integration', 'Automated patient positioning system', 'Respiratory gating with 4D-CT support', 'MOSAIQ oncology information system link'],
    specs: [{ label: 'MLC', value: 'Agility 160 leaves, 2.5 mm' }, { label: 'Max Dose Rate', value: '2200 MU/min (10 MV FFF)' }, { label: 'Energies', value: '6–15 MV photons, 6–22 MeV electrons' }, { label: 'Imaging', value: 'XVI kV CBCT' }, { label: 'Certifications', value: 'CE, FDA, IEC 60601-2-1' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'IEC 60601-2-1'],
    isNew: true,
    isFeatured: false,
  },

  // ── GENERAL WARD EQUIPMENT ─────────────────────────────────────────────────
  {
    id: 22,
    name: 'Linet Multicare Hospital Bed',
    sku: 'LNT-MLC-IP-5',
    category: 'General Ward Equipment',
    manufacturer: 'Linet',
    country: 'Czech Republic',
    image: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=900&q=80',
    description: 'Motorised acute care hospital bed with pressure injury prevention and integrated nurse call system.',
    fullDescription: 'The Linet Multicare IP is a versatile motorised hospital bed designed for acute care wards. Its IntelliFrame technology actively detects early signs of pressure injury development and prompts repositioning, while the integrated fall detection and nurse call system enhances patient safety. The lightweight aluminium frame simplifies cleaning and infection control compliance.',
    features: ['IntelliFrame pressure injury prevention', 'Integrated fall detection and nurse call', 'Motorised height, backrest, and knee-break adjustment', 'CPR-ready position in <5 seconds', 'Aluminium frame for easy decontamination', 'Siderails with integrated patient controls', 'IV pole and oxygen cylinder holders', 'Bed-exit detection sensor integration'],
    specs: [{ label: 'Height Range', value: '350–800 mm' }, { label: 'Max Load', value: '250 kg' }, { label: 'Backrest Angle', value: '0–75°' }, { label: 'Weight', value: '145 kg (base)' }, { label: 'Certifications', value: 'CE, ISO 13485, IEC 60601-1' }],
    certifications: ['CE Mark', 'ISO 13485', 'IEC 60601-1'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 23,
    name: 'Omron HBP-1300 Professional BP Monitor',
    sku: 'OMR-HBP1300-PRO',
    category: 'General Ward Equipment',
    manufacturer: 'Omron Healthcare',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&q=80',
    description: 'Validated professional blood pressure monitor with arrhythmia detection and large memory for ward rounds.',
    fullDescription: 'The Omron HBP-1300 is a clinically validated upper-arm blood pressure monitor designed for professional healthcare settings. With IntelliSense technology for optimal cuff inflation and AFIB detection integrated into every measurement, it provides highly accurate readings even in irregular heartbeat patients. The 100-reading memory with time and date stamp supports ward documentation.',
    features: ['IntelliSense automatic cuff inflation optimisation', 'AFIB (atrial fibrillation) detection per measurement', '100-reading memory with time/date stamp', 'Large backlit display for easy ward reading', 'Irregular heartbeat indicator', 'Average of last 3 readings function', 'AC adapter and battery operation', 'Validated for clinical use (ESH grade A)'],
    specs: [{ label: 'Measurement Method', value: 'Oscillometric' }, { label: 'Cuff Size', value: '22–42 cm standard cuff' }, { label: 'Memory', value: '100 readings with time/date' }, { label: 'Accuracy', value: '±3 mmHg' }, { label: 'Certifications', value: 'CE, ESH Grade A, ISO 81060' }],
    certifications: ['CE Mark', 'ESH Grade A', 'ISO 81060'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 24,
    name: 'Welch Allyn Connex Vital Signs Monitor',
    sku: 'WA-CVSP-6000',
    category: 'General Ward Equipment',
    manufacturer: 'Welch Allyn (Baxter)',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1576669801820-a9ab287ac2d1?w=900&q=80',
    description: 'Portable vital signs monitor for ward rounds with wireless EMR integration and automated early warning scoring.',
    fullDescription: 'The Welch Allyn Connex Vital Signs Monitor 6000 is designed for mobile ward rounds and multi-patient assessment. It acquires all vital signs — NIBP, SpO2, temperature, and pulse rate — in under 60 seconds and automatically calculates NEWS/NEWS2 early warning scores, pushing results wirelessly to the EMR via WiFi or Bluetooth.',
    features: ['Complete vital signs in under 60 seconds', 'Automated NEWS/NEWS2 early warning score', 'Wireless EMR push via WiFi and Bluetooth', 'Integrated SureTemp Plus thermometry', 'Masimo SET SpO2 motion-tolerant technology', 'Barcode patient identification scanning', 'Touchscreen with glove-friendly operation', '8-hour battery for full shift use'],
    specs: [{ label: 'Parameters', value: 'NIBP, SpO2, Temp, Pulse Rate' }, { label: 'NIBP Method', value: 'Oscillometric' }, { label: 'Connectivity', value: 'WiFi 802.11, Bluetooth' }, { label: 'Battery', value: '8 hours continuous' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'],
    isNew: true,
    isFeatured: false,
  },

  // ── MATERNAL & INFANT CARE ─────────────────────────────────────────────────
  {
    id: 25,
    name: 'GE Voluson E10 Obstetric Ultrasound',
    sku: 'GE-VOL-E10-OB',
    category: 'Maternal & Infant Care',
    manufacturer: 'GE Healthcare',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=900&q=80',
    description: 'Premium 4D obstetric ultrasound with HDlive rendering, foetal heart rate analysis, and automated biometry.',
    fullDescription: 'The GE Voluson E10 is the gold standard for obstetric ultrasound, offering HDlive 4D rendering for lifelike foetal imaging, automated OB biometry measurements, and AI-powered foetal cardiac screening. Its advanced colour flow Doppler and spectral analysis tools provide comprehensive assessment of foetal and maternal vascular status throughout pregnancy.',
    features: ['HDlive 4D rendering with silhouette mode', 'Automated OB biometry (BPD, HC, AC, FL)', 'AI-powered foetal cardiac screening', 'SonoVCAD Heart foetal echocardiography', 'Cervical length measurement tools', 'Foetal weight estimation with Z-scores', 'Placental vascularity assessment', 'Cloud-based sharing and reporting'],
    specs: [{ label: 'Modes', value: '2D, 3D, 4D, Doppler, CEUS' }, { label: 'Frame Rate', value: '>500 fps 2D' }, { label: 'Display', value: '21.5" HD touchscreen' }, { label: 'Probes', value: 'Curvilinear, transvaginal, 3D/4D' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: 26,
    name: 'Dräger Caleo Neonatal Incubator',
    sku: 'DRG-CALEO-NEONIC',
    category: 'Maternal & Infant Care',
    manufacturer: 'Dräger',
    country: 'Germany',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&q=80',
    description: 'Closed neonatal incubator with servo-controlled temperature, humidity, and integrated X-ray capability.',
    fullDescription: 'The Dräger Caleo is a closed neonatal incubator engineered for the care of premature and critically ill newborns. Its servo-controlled air and skin temperature mode provides precise thermal management, while the integrated humidification system maintains optimal humidity levels to prevent transepidermal water loss. The X-ray cassette drawer enables imaging without removing the infant.',
    features: ['Servo-controlled air and skin temperature', 'Integrated humidification (up to 95% RH)', 'X-ray cassette drawer for bedside imaging', 'Double-wall construction for heat retention', 'Low-noise environment (<45 dB)', 'Tilt function for drainage positioning', 'Integrated scale option (±5 g accuracy)', 'Phototherapy light compatibility'],
    specs: [{ label: 'Temperature Range', value: '25–37°C (air mode)' }, { label: 'Humidity', value: 'Up to 95% RH' }, { label: 'Patient Weight', value: 'Up to 10 kg' }, { label: 'Noise Level', value: '<45 dB' }, { label: 'Certifications', value: 'CE, ISO 13485, IEC 60601-1' }],
    certifications: ['CE Mark', 'ISO 13485', 'IEC 60601-1'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: 27,
    name: 'Philips Avalon FM50 Foetal Monitor',
    sku: 'PHL-AVL-FM50-CTG',
    category: 'Maternal & Infant Care',
    manufacturer: 'Philips',
    country: 'Netherlands',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=900&q=80',
    description: 'Foetal and maternal monitor with intelligent CTG analysis, wireless telemetry, and central station integration.',
    fullDescription: 'The Philips Avalon FM50 is a comprehensive foetal and maternal monitor for labour and delivery. It supports simultaneous foetal heart rate and uterine activity monitoring via both external and internal sensors, with automated CTG interpretation and intelligent decelerations classification. Wireless telemetry enables ambulatory monitoring during labour.',
    features: ['Simultaneous maternal and foetal monitoring', 'Intelligent CTG analysis with FIGO/ACOG classification', 'Wireless telemetry for ambulatory labour monitoring', 'Central station and EMR integration', 'Maternal SpO2, NIBP, and ECG monitoring options', 'Waterproof telemetry unit for hydrotherapy', 'Intrapartum doppler and TOCO transducers', 'Automated FHR variability analysis'],
    specs: [{ label: 'FHR Range', value: '50–240 bpm' }, { label: 'TOCO Sensitivity', value: '1–100 kPa' }, { label: 'Wireless', value: 'IEEE 802.11 a/b/g/n' }, { label: 'Display', value: '12.1" colour touchscreen' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'],
    isNew: true,
    isFeatured: false,
  },

  // ── ANAESTHESIA SYSTEMS ────────────────────────────────────────────────────
  {
    id: 28,
    name: 'GE Datex-Ohmeda Aisys CS2 Anaesthesia',
    sku: 'GE-AISYS-CS2-ADV',
    category: 'Anaesthesia Systems',
    manufacturer: 'GE Healthcare',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=900&q=80',
    description: 'Advanced anaesthesia delivery system with integrated ventilation, agent delivery, and multi-parameter monitoring.',
    fullDescription: 'The GE Aisys CS2 is an advanced anaesthesia workstation that integrates precision agent delivery, advanced ventilation modes, and comprehensive patient monitoring into a single ergonomic platform. The Carestation software suite enables electronic anaesthesia records, drug dosage calculators, and seamless integration with hospital information systems.',
    features: ['Integrated Agent Delivery System (ADS)', 'Advanced ventilation modes (PCV-VG, SIMV)', 'Electronic flow control with low-flow optimisation', 'Carestation automated anaesthesia records', 'Integrated monitoring: ECG, SpO2, NIBP, EtCO2, agents', 'SmartVent advanced ventilator', 'Integrated drug and dosing calculator', 'Compatible with all major anaesthetic agents'],
    specs: [{ label: 'Ventilation Modes', value: 'VCV, PCV, SIMV, PSV, PCV-VG' }, { label: 'Flow Range', value: '0.2–18 L/min' }, { label: 'Agent Vaporisers', value: '2 simultaneous agent slots' }, { label: 'Display', value: '15" colour touchscreen' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: 29,
    name: 'Dräger Perseus A500 Anaesthesia Workstation',
    sku: 'DRG-PER-A500-OR',
    category: 'Anaesthesia Systems',
    manufacturer: 'Dräger',
    country: 'Germany',
    image: 'https://images.unsplash.com/photo-1576669801820-a9ab287ac2d1?w=900&q=80',
    description: 'High-end anaesthesia workstation with ERC electronic gas management and full physiological monitoring integration.',
    fullDescription: 'The Dräger Perseus A500 sets the standard for anaesthesia workstation design, combining the most advanced agent delivery technology with a comprehensive monitoring platform. The electronic gas delivery system (ERC) eliminates traditional flowmeters, providing precise low-flow anaesthesia with up to 90% agent savings. Full integration with the Infinity monitoring platform delivers complete intraoperative physiological data.',
    features: ['ERC electronic breathing system control', 'Low-flow anaesthesia with up to 90% agent savings', 'Integrated Infinity patient monitoring', 'Automated pre-use checks (BSPM)', 'SmartPilot View anaesthesia guidance display', 'EtCO2, SpO2, NIBP, ECG, neuromuscular monitoring', 'Drug and pharmacokinetic models (PK/PD)', 'Compatible with Dräger Scio anaesthesia information system'],
    specs: [{ label: 'Gas Delivery', value: 'ERC electronic flow control' }, { label: 'Ventilation Modes', value: 'VCV, PCV, SIMV, PSV, APRV, BiLevel' }, { label: 'Agent Vaporisers', value: '2 simultaneous (DIVA or Vapor)' }, { label: 'Fresh Gas Flow', value: '0.1–18 L/min' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'],
    isNew: true,
    isFeatured: false,
  },
  {
    id: 30,
    name: 'Masimo Root Patient Safety Monitor',
    sku: 'MSM-ROOT-ANESTH',
    category: 'Anaesthesia Systems',
    manufacturer: 'Masimo',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=900&q=80',
    description: 'Multimodal patient safety monitoring platform for anaesthesia and sedation with rainbow SET multi-wavelength pulse oximetry.',
    fullDescription: 'The Masimo Root is a bedside patient safety and connectivity hub that combines the most comprehensive non-invasive monitoring with powerful data integration capabilities. At its core, rainbow SET technology measures SpO2, SpCO, SpMet, SpHb, and SpO2R — parameters beyond conventional pulse oximetry — providing anaesthetists with an unprecedented window into patient haemodynamic and respiratory status during procedures.',
    features: ['rainbow SET multi-wavelength oximetry (SpO2, SpCO, SpMet, SpHb)', 'Total Haemoglobin (SpHb) non-invasive monitoring', 'Sedation assessment with SedLine brain function monitor option', 'Noninvasive haemoglobin trending', 'Integrated NIBP, capnography, and temperature', 'Open connectivity hub for third-party devices', 'Masimo SafetyNet remote monitoring integration', 'HL7 and EMR bidirectional data exchange'],
    specs: [{ label: 'SpO2 Accuracy', value: '±1.5% (70–100%)' }, { label: 'SpHb Accuracy', value: '±1.5 g/dL' }, { label: 'Display', value: '15" HD touchscreen' }, { label: 'Connectivity', value: 'WiFi, Ethernet, HL7, DICOM' }, { label: 'Certifications', value: 'CE, FDA, ISO 13485' }],
    certifications: ['CE Mark', 'FDA 510(k)', 'ISO 13485'],
    isNew: false,
    isFeatured: false,
  },
];

export const categories = [
  'All Categories',
  'Theatre Equipment',
  'ICU Equipment',
  'Emergency Equipment',
  'Orthopaedic Devices',
  'Diagnostic Equipment',
  'Cardiology Equipment',
  'Laboratory Equipment',
  'Radiology Equipment',
  'Digital Health Systems',
  'CSSD Equipment',
  'Oncology Equipment',
  'General Ward Equipment',
  'Maternal & Infant Care',
  'Anaesthesia Systems',
];